mongo-express:
        image: mongo-express
        container_name: mongo-express
        ports:
            - 8081:8081
        volumes:
            - ./.docker/mongo-express/docker-entrypoint.sh:/docker-entrypoint.sh
        env_file:
            - .env
        environment:
            ME_CONFIG_MONGODB_SERVER: mongodb
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
        depends_on:
            - mongodb
